version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your_password_here
      - POSTGRES_DB=farmhelperservice
    volumes:
      - ./src/FarmHelperService/Data/Migrations:/docker-entrypoint-initdb.d