version: "3.8"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=ChangeMe123!
    ports:
      - "1433:1433"
    volumes:
      - ./mssqldata:/var/opt/mssql/data
