version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your_password_here
      - POSTGRES_DB=farmhelperservice
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data